"""claude_client.py — Claude API interactions and conversation history.

Key design decisions:
- The Garmin data summary is embedded in the system prompt, not in the first
  user message. This keeps it invisible to the user's chat history and lets
  Claude reference it throughout the conversation without it being re-sent.
- Conversation history is stored as a plain list of {role, content} dicts —
  exactly what the Messages API expects — so follow-up questions work naturally.
- When a history_file path is supplied (web UI), history is persisted to disk
  and reloaded on the next startup so conversations survive server restarts.
  digest.py and the CLI omit history_file and always start fresh.
- Model and token cap are module-level constants for easy tuning.
"""

import json
from datetime import datetime
from pathlib import Path

from anthropic import Anthropic, AsyncAnthropic

MODEL = "claude-sonnet-4-6"

# Max tokens per response — enough for detailed coaching advice without being verbose
MAX_TOKENS = 4096

# History compression: keep the active (API-sent) window small to control token cost.
# Turns beyond ARCHIVE_TRIGGER are moved to a side-car archive file in batches.
MAX_ACTIVE_TURNS = 60   # target size after archiving
ARCHIVE_TRIGGER  = 80   # archive fires when history grows past this
ARCHIVE_BATCH    = 20   # turns moved per archive pass


class ClaudeCoach:
    """
    Manages a stateful coaching conversation with Claude.

    The health summary is baked into the system prompt once at construction;
    all subsequent chat() calls append to a growing message history.

    If history_file is provided, the conversation is persisted to disk and
    reloaded on the next startup — so Claude remembers previous sessions.
    """

    def __init__(self, health_summary: str, history_file: Path | None = None):
        self.client = Anthropic()
        self.async_client = AsyncAnthropic()
        self._history_file = history_file
        self.history: list[dict] = self._load_history()
        self._base_system_prompt = self._build_system_prompt(health_summary)
        self._persona_content: str | None = None
        self.system_prompt = self._base_system_prompt

    def _load_history(self) -> list[dict]:
        """Load persisted conversation history from disk, or return an empty list."""
        if self._history_file and self._history_file.exists():
            try:
                return json.loads(self._history_file.read_text(encoding="utf-8"))
            except Exception:
                pass
        return []

    def _archive_history(self) -> None:
        """
        When history exceeds ARCHIVE_TRIGGER turns, move the oldest ARCHIVE_BATCH
        turns to a side-car archive file so the active window stays bounded.

        Archived turns are preserved in data/chat_history_claude_archive.json
        (each call appends a timestamped batch) but are never sent to the API.
        Silent failure — archiving is non-fatal.
        """
        if len(self.history) <= ARCHIVE_TRIGGER or not self._history_file:
            return

        to_archive = self.history[:ARCHIVE_BATCH]
        self.history = self.history[ARCHIVE_BATCH:]

        archive_file = self._history_file.parent / (
            self._history_file.stem + "_archive.json"
        )
        try:
            existing = (
                json.loads(archive_file.read_text(encoding="utf-8"))
                if archive_file.exists()
                else []
            )
        except Exception:
            existing = []

        existing.append({
            "archived_at": datetime.now().isoformat(timespec="seconds"),
            "turns": to_archive,
        })
        try:
            archive_file.write_text(
                json.dumps(existing, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
        except Exception:
            pass

    def _save_history(self) -> None:
        """Persist current conversation history to disk, archiving old turns first."""
        self._archive_history()
        if self._history_file:
            try:
                self._history_file.write_text(
                    json.dumps(self.history, indent=2, ensure_ascii=False),
                    encoding="utf-8",
                )
            except Exception:
                pass

    def _build_system_prompt(self, health_summary: str) -> str:
        return f"""You are a personal health and fitness coach running inside the user's Garmin Health Coach app.

About this app:
- Your conversation history is automatically saved and reloaded on the next session, so you will remember previous conversations.
- The app includes a Daily Digest feature: a scheduled email sent each morning with yesterday's health summary and a coaching recommendation generated by you. The user can enable and configure it in Settings.
- Garmin data is fetched fresh from the user's Garmin Connect account each time the app starts.

Your coaching style:
- Be concise and actionable — skip preambles, get to the insight
- Reference specific numbers from the data when relevant
- Spot trends and patterns across days, not just single-day snapshots
- Be encouraging but honest; flag concerning patterns (e.g., chronic high stress, poor sleep)
- When the user asks general questions, ground your answer in their actual data

Here is the user's recent Garmin health data:

{health_summary}

Use this data to answer questions and give personalized recommendations."""

    def set_persona(self, persona_content: str) -> None:
        """Overlay a coaching persona on the base system prompt."""
        self._persona_content = persona_content
        self.system_prompt = (
            self._base_system_prompt
            + "\n\n---\n\n"
            + persona_content
        )

    def clear_persona(self) -> None:
        """Remove the active persona and restore the base system prompt."""
        self._persona_content = None
        self.system_prompt = self._base_system_prompt

    @property
    def active_persona(self) -> bool:
        return self._persona_content is not None

    def chat(self, user_message: str) -> str:
        """
        Send a user message, get a response, and update history.

        The full conversation history is sent on every call so Claude has
        context for follow-up questions ("what about yesterday?" etc.).
        """
        self.history.append({"role": "user", "content": user_message})

        response = self.client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=self.system_prompt,
            messages=self.history,
        )

        reply = response.content[0].text
        self.history.append({"role": "assistant", "content": reply})
        self._save_history()
        return reply

    def chat_stream(self, user_message: str):
        """
        Sync generator that yields text chunks as Claude produces them.
        Used by the CLI (main.py). Updates history when complete.
        """
        self.history.append({"role": "user", "content": user_message})
        full_reply = ""
        with self.client.messages.stream(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=self.system_prompt,
            messages=self.history,
        ) as stream:
            for chunk in stream.text_stream:
                full_reply += chunk
                yield chunk
        self.history.append({"role": "assistant", "content": full_reply})
        self._save_history()

    async def chat_stream_async(self, user_message: str):
        """
        Async generator that yields text chunks as Claude produces them.
        Used by the web server (server.py) via SSE. Updates history when complete.
        """
        self.history.append({"role": "user", "content": user_message})
        full_reply = ""
        async with self.async_client.messages.stream(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=self.system_prompt,
            messages=self.history,
        ) as stream:
            async for chunk in stream.text_stream:
                full_reply += chunk
                yield chunk
        self.history.append({"role": "assistant", "content": full_reply})
        self._save_history()

    def reset_history(self) -> None:
        """Clear conversation history and remove the persisted history file."""
        self.history = []
        if self._history_file and self._history_file.exists():
            self._history_file.unlink(missing_ok=True)
